const vehicleCode = document.getElementById("vehicle-code");
const searchCity = document.getElementById("Find-City");
const reset = document.getElementById("Reset-City");
const cityresult = document.getElementById("result");

const vehicledata = {
"AP39": "Amaravati - Andhra Pradesh",
"AP31": "Visakhapatnam - Andhra Pradesh",
"AP16": "Vijayawada - Andhra Pradesh",
"AP07": "Guntur - Andhra Pradesh",
"AP26": "Nellore - Andhra Pradesh",
"AP21": "Kurnool - Andhra Pradesh",
"AP02": "Kadapa (Cuddapah) - Andhra Pradesh",
"AP05": "Rajahmundry - Andhra Pradesh",
"AP03": "Tirupati - Andhra Pradesh",
"AP22": "Anantapur - Andhra Pradesh",
"AP18": "Vizianagaram - Andhra Pradesh",
"AP04": "Eluru - Andhra Pradesh",
"AP23": "Ongole - Andhra Pradesh",
"AP24": "Nandyal - Andhra Pradesh",
"AP06": "Machilipatnam - Andhra Pradesh",
"AP20": "Adoni - Andhra Pradesh",
"AP8": "Tenali - Andhra Pradesh",
"AP27": "Proddatur - Andhra Pradesh",
"AP01": "Chittoor - Andhra Pradesh",
"AP25": "Hindupur - Andhra Pradesh",
"AP10": "Bhimavaram - Andhra Pradesh",
"AP29": "Madanapalle - Andhra Pradesh",
"AP19": "Srikakulam - Andhra Pradesh",
"AP32": "Tadipatri - Andhra Pradesh",
"AP33": "Dharmavaram - Andhra Pradesh",
"AS01": "Guwahati- Assam",
"AS11": "Silchar- Assam",
"AS07": "Dibrugarh- Assam",
"AS06": "Jorhat- Assam",
"AS09": "Tezpur- Assam",
"AS05": "Nagaon- Assam",
"AS03": "Tinsukia- Assam",
"AS04": "Bongaigaon- Assam",
"AS10": "Kokrajhar- Assam",
"AS12": "Dhubri- Assam",
"AS02": "Golaghat- Assam",
"AS15": "Hailakandi- Assam",
"AS14": "Karimganj- Assam",
"AS8": "Sivasagar- Assam",
"AS16": "Barpeta- Assam",
"AS13": "Goalpara- Assam",
"AS17": "Lakhimpur- Assam",
"AS18": "Nalbari- Assam",
"AS19": "Sonitpur (Tezpur)- Assam",
"AS20": "Baksa (Mushalpur)- Assam",
"AS21": "Kamrup (Rural)- Assam",
"AS22": "Chirang (Kajalgaon)- Assam",
"AS23": "Udalguri (Tangla)- Assam",
"AS24": "Dima Hasao (Haflong)- Assam",
"AS25": "Karbi Anglong (Diphu)- Assam",
"AS26": "Hailakandi (Hailakandi)- Assam",
"AS27": "Karimganj (Karimganj)- Assam",
"AS28": "Baksa (Barama)- Assam",
"AS29": "Charaideo (Sonari)- Assam",
"AS30": "Hojai (Hojai)- Assam",
"AS31": "Biswanath (Biswanath Chariali)- Assam",
"BR01": "Patna - Bihar",
"BR02": "Gaya - Bihar",
"BR03": "Bhagalpur - Bihar",
"BR04": "Muzaffarpur - Bihar",
"BR05": "Darbhanga - Bihar",
"BR06": "Motihari - Bihar",
"BR07": "Bettiah - Bihar",
"BR8": "Chapra - Bihar",
"BR09": "Purnia - Bihar",
"BR10": "Munger - Bihar",
"BR11": "Aurangabad - Bihar",
"BR12": "Samastipur - Bihar",
"BR13": "Buxar - Bihar",
"BR14": "Supaul - Bihar",
"BR15": "Siwan - Bihar",
"BR16": "Begusarai - Bihar",
"BR17": "Saharsa - Bihar",
"BR18": "Sasaram - Bihar",
"BR19": "Hajipur - Bihar",
"BR20": "Dehri-on-Sone - Bihar",
"BR21": "Sasaram - Bihar",
"BR22": "Bhojpur - Bihar",
"BR23": "Madhubani - Bihar",
"BR24": "Katihar - Bihar",
"BR25": "Sitamarhi - Bihar",
"BR26": "Munger - Bihar",
"BR27": "Madhepura - Bihar",
"BR28": "Khagaria - Bihar",
"BR29": "Araria - Bihar",
"BR30": "Buxar - Bihar",
"BR31": "Kishanganj - Bihar",
"BR32": "Jehanabad - Bihar",
"BR33": "Arwal - Bihar",
"BR34": "Sheikhpura - Bihar",
"BR35": "Nawada - Bihar",
"BR36": "Jamui - Bihar",
"CG01": "Raipur - Chhattisgarh",
"CG04": "Bilaspur - Chhattisgarh",
"CG06": "Durg - Chhattisgarh",
"CG07": "Bhilai - Chhattisgarh",
"CG05": "Raigarh - Chhattisgarh",
"CG8": "Korba - Chhattisgarh",
"CG02": "Jagdalpur - Chhattisgarh",
"CG03": "Ambikapur - Chhattisgarh",
"CG09": "Rajnandgaon - Chhattisgarh",
"CG10": "Janjgir - Chhattisgarh",
"CG11": "Kawardha - Chhattisgarh",
"CG12": "Dhamtari - Chhattisgarh",
"CG13": "Mahasamund - Chhattisgarh",
"CG14": "Kanker - Chhattisgarh",
"CG15": "Bastar - Chhattisgarh",
"CG16": "Surguja - Chhattisgarh",
"CG17": "Baloda Bazar - Chhattisgarh",
"CG18": "Mungeli - Chhattisgarh",
"CG19": "Surajpur - Chhattisgarh",
"CG20": "Balrampur - Chhattisgarh",
"CG21": "Bemetara - Chhattisgarh",
"CG22": "Bijapur - Chhattisgarh",
"CG23": "Narayanpur - Chhattisgarh",
"CG24": "Gariaband - Chhattisgarh",
"CG25": "Balod - Chhattisgarh",
"CG26": "Sukma - Chhattisgarh",
"CG27": "Kondagaon - Chhattisgarh",
"CG28": "Baloda - Chhattisgarh",
"CG29": "Mungeli - Chhattisgarh",
"CG30": "Gaurela-Pendra-Marwahi - Chhattisgarh",
"GA01": "Panaji (Panjim) - Goa",
"GA02": "Margao - Goa",
"GA03": "Vasco da Gama - Goa",
"GA04": "Mapusa - Goa",
"GA05": "Bicholim - Goa",
"GA06": "Ponda - Goa",
"GA07": "Quepem - Goa",
"GA8": "Sanguem - Goa",
"GA09": "Dharbandora - Goa",
"GA10": "North Goa - Goa",
"GA11": "South Goa - Goa",
"GJ01": "Ahmedabad - Gujarat",
"GJ05": "Surat - Gujarat",
"GJ06": "Vadodara - Gujarat",
"GJ03": "Rajkot - Gujarat",
"GJ04": "Bhavnagar - Gujarat",
"GJ07": "Jamnagar - Gujarat",
"GJ10": "Junagadh - Gujarat",
"GJ02": "Gandhinagar - Gujarat",
"GJ18": "Nadiad - Gujarat",
"GJ23": "Anand - Gujarat",
"GJ16": "Bharuch - Gujarat",
"GJ21": "Navsari - Gujarat",
"GJ19": "Valsad - Gujarat",
"GJ13": "Surendranagar - Gujarat",
"GJ24": "Mehsana - Gujarat",
"GJ27": "Palanpur - Gujarat",
"GJ12": "Bhuj - Gujarat",
"GJ21": "Porbandar - Gujarat",
"GJ19": "Godhra - Gujarat",
"GJ35": "Botad - Gujarat",
"GJ09": "Amreli - Gujarat",
"GJ8": "Morbi - Gujarat",
"GJ18": "Dahod - Gujarat",
"GJ24": "Patan - Gujarat",
"GJ20": "Vapi - Gujarat",
"GJ40": "Veraval - Gujarat",
"GJ06": "Gandhidham - Gujarat",
"HR01": "Ambala - Haryana",
"HR02": "Yamunanagar - Haryana",
"HR03": "Kurukshetra - Haryana",
"HR04": "Karnal - Haryana",
"HR05": "Panipat - Haryana",
"HR06": "Sonipat - Haryana",
"HR07": "Jind - Haryana",
"HR8": "Rohtak - Haryana",
"HR09": "Hisar - Haryana",
"HR10": "Bhiwani - Haryana",
"HR11": "Sirsa - Haryana",
"HR12": "Gurgaon (Gurugram) - Haryana",
"HR13": "Faridabad - Haryana",
"HR14": "Palwal - Haryana",
"HR15": "Rewari - Haryana",
"HR16": "Narnaul - Haryana",
"HR17": "Kaithal - Haryana",
"HR18": "Gohana - Haryana",
"HR19": "Panchkula - Haryana",
"HR20": "Ambala Cantt - Haryana",
"HR21": "Thanesar - Haryana",
"HR22": "Fatehabad - Haryana",
"HR23": "Tohana - Haryana",
"HR24": "Dabwali - Haryana",
"HR25": "Charkhi Dadri - Haryana",
"HR26": "Narwana - Haryana",
"HR27": "Ellenabad - Haryana",
"HR28": "Hansi - Haryana",
"HR29": "Bahadurgarh - Haryana",
"HR30": "Bawal - Haryana",
"HR31": "Faridabad-NIT - Haryana",
"HR32": "Hodal - Haryana",
"HR33": "Jagadhri - Haryana",
"HR34": "Kosli - Haryana",
"HR35": "Loharu - Haryana",
"HR36": "Naraingarh - Haryana",
"HR37": "Nuh - Haryana",
"HR38": "Palwal (old) - Haryana",
"HR39": "Pehowa - Haryana",
"HR40": "Safidon - Haryana",
"HR41": "Shahbad - Haryana",
"HR42": "Sirsa (old) - Haryana",
"HR43": "Uklana - Haryana",
"HR44": "Yamunanagar (old) - Haryana",
"HP01": "Shimla - Himachal Pradesh",
"HP02": "Solan - Himachal Pradesh",
"HP03": "Mandi - Himachal Pradesh",
"HP04": "Chamba - Himachal Pradesh",
"HP05": "Kangra - Himachal Pradesh",
"HP06": "Hamirpur - Himachal Pradesh",
"HP07": "Una - Himachal Pradesh",
"HP8": "Bilaspur - Himachal Pradesh",
"HP09": "Kullu - Himachal Pradesh",
"HP10": "Lahaul and Spiti - Himachal Pradesh",
"HP11": "Kinnaur - Himachal Pradesh",
"HP12": "Sirmaur (Nahan) - Himachal Pradesh",
"JH01": "Ranchi - Jharkhand",
"JH02": "Jamshedpur - Jharkhand",
"JH03": "Dhanbad - Jharkhand",
"JH04": "Bokaro Steel City - Jharkhand",
"JH05": "Hazaribagh - Jharkhand",
"JH06": "Deoghar - Jharkhand",
"JH07": "Giridih - Jharkhand",
"JH8": "Koderma - Jharkhand",
"JH09": "Ramgarh - Jharkhand",
"JH10": "Chaibasa - Jharkhand",
"JH11": "Dumka - Jharkhand",
"JH12": "Palamau - Jharkhand",
"JH13": "Simdega - Jharkhand",
"JH14": "Latehar - Jharkhand",
"JH15": "Jamtara - Jharkhand",
"JH16": "Godda - Jharkhand",
"JH17": "Sahebganj - Jharkhand",
"JH18": "Pakur - Jharkhand",
"JH19": "Saraikela-Kharsawan - Jharkhand",
"JH20": "Gumla - Jharkhand",
"JH21": "Lohardaga - Jharkhand",
"JH22": "West Singhbhum - Jharkhand",
"JH23": "Khunti - Jharkhand",
"JH24": "Chatra - Jharkhand",
"JH25": "Garhwa - Jharkhand",
"JH26": "Simdega - Jharkhand",
"JH27": "Jamshedpur (old) - Jharkhand",
"KA01": "Bangalore (Bengaluru) - Karnataka",
"KA06": "Belgaum - Karnataka",
"KA33": "Bellary - Karnataka",
"KA28": "Bijapur - Karnataka",
"KA29": "Chamarajanagar - Karnataka",
"KA10": "Chickmagalur - Karnataka",
"KA17": "Chitradurga - Karnataka",
"KA16": "Davangere - Karnataka",
"KA07": "Dharwad - Karnataka",
"KA26": "Gadag - Karnataka",
"KA32": "Gulbarga - Karnataka",
"KA13": "Hassan - Karnataka",
"KA27": "Haveri - Karnataka",
"KA12": "Kodagu (Madikeri) - Karnataka",
"KA09": "Kolar - Karnataka",
"KA31": "Koppal - Karnataka",
"KA11": "Mandya - Karnataka",
"KA55": "Mysore (Mysuru) - Karnataka",
"KA34": "Raichur - Karnataka",
"KA53": "Ramanagara - Karnataka",
"KA14": "Shimoga - Karnataka",
"KA06": "Tumkur - Karnataka",
"KA20": "Udupi - Karnataka",
"KA30": "Uttara Kannada (Karwar) - Karnataka",
"KA35": "Yadgir - Karnataka",
"KL01": "Thiruvananthapuram - Kerala",
"KL02": "Kollam - Kerala",
"KL03": "Pathanamthitta - Kerala",
"KL04": "Alappuzha - Kerala",
"KL05": "Kottayam - Kerala",
"KL06": "Idukki - Kerala",
"KL07": "Ernakulam (Kochi) - Kerala",
"KL8": "Thrissur - Kerala",
"KL09": "Palakkad - Kerala",
"KL10": "Malappuram - Kerala",
"KL11": "Kozhikode - Kerala",
"KL12": "Wayanad - Kerala",
"KL13": "Kannur - Kerala",
"KL14": "Kasaragod - Kerala",
"MP01": "Bhopal - Madhya Pradesh",
"MP09": "Indore - Madhya Pradesh",
"MP04": "Jabalpur - Madhya Pradesh",
"MP07": "Gwalior - Madhya Pradesh",
"MP12": "Ujjain - Madhya Pradesh",
"MP06": "Rewa - Madhya Pradesh",
"MP11": "Sagar - Madhya Pradesh",
"MP15": "Satna - Madhya Pradesh",
"MP46": "Ratlam - Madhya Pradesh",
"MP23": "Katni - Madhya Pradesh",
"MP18": "Dhar - Madhya Pradesh",
"MP10": "Khandwa - Madhya Pradesh",
"MP28": "Chhindwara - Madhya Pradesh",
"MP43": "Burhanpur - Madhya Pradesh",
"MP19": "Hoshangabad - Madhya Pradesh",
"MP8": "Vidisha - Madhya Pradesh",
"MP36": "Chhatarpur - Madhya Pradesh",
"MP24": "Damoh - Madhya Pradesh",
"MP45": "Mandsaur - Madhya Pradesh",
"MP47": "Khargone - Madhya Pradesh",
"MP48": "Neemuch - Madhya Pradesh",
"MP25": "Sehore - Madhya Pradesh",
"MP26": "Harda - Madhya Pradesh",
"MP27": "Betul - Madhya Pradesh",
"MP37": "Shivpuri - Madhya Pradesh",
"MP64": "Anuppur - Madhya Pradesh",
"MP38": "Ashoknagar - Madhya Pradesh",
"MP49": "Barwani - Madhya Pradesh",
"MP50": "Alirajpur - Madhya Pradesh",
"MP66": "Singrauli - Madhya Pradesh",
"MP34": "Dewas - Madhya Pradesh",
"MP74": "Dindori - Madhya Pradesh",
"MP65": "Shahdol - Madhya Pradesh",
"MP67": "Sidhi - Madhya Pradesh",
"MP72": "Agar Malwa - Madhya Pradesh",
"MP73": "Sheopur - Madhya Pradesh",
"MP75": "Datia - Madhya Pradesh",
"MP76": "Narsinghpur - Madhya Pradesh",
"MP51": "Shajapur - Madhya Pradesh",
"MP29": "Guna - Madhya Pradesh",
"MP31": "Rajgarh - Madhya Pradesh",
"MH01": "Mumbai (Greater Mumbai) - Maharashtra",
"MH05": "Thane - Maharashtra",
"MH12": "Pune - Maharashtra",
"MH15": "Nashik - Maharashtra",
"MH13": "Solapur - Maharashtra",
"MH31": "Nagpur - Maharashtra",
"MH09": "Kolhapur - Maharashtra",
"MH20": "Aurangabad - Maharashtra",
"MH27": "Amravati - Maharashtra",
"MH24": "Latur - Maharashtra",
"MH8": "Ratnagiri - Maharashtra",
"MH11": "Satara - Maharashtra",
"MH10": "Sangli - Maharashtra",
"MH28": "Beed - Maharashtra",
"MH19": "Jalgaon - Maharashtra",
"MH26": "Nanded - Maharashtra",
"MH32": "Chandrapur - Maharashtra",
"MH18": "Dhule - Maharashtra",
"MH21": "Jalna - Maharashtra",
"MH25": "Parbhani - Maharashtra",
"MH30": "Akola - Maharashtra",
"MH28": "Buldhana - Maharashtra",
"MH38": "Hingoli - Maharashtra",
"MH22": "Osmanabad - Maharashtra",
"MH36": "Gondia - Maharashtra",
"MH35": "Gadchiroli - Maharashtra",
"MH37": "Washim - Maharashtra",
"MH34": "Wardha - Maharashtra",
"MH29": "Yavatmal - Maharashtra",
"MH33": "Bhandara - Maharashtra",
"MH07": "Sindhudurg - Maharashtra",
"MH06": "Raigad - Maharashtra",
"MH8": "Ratnagiri - Maharashtra",
"MH21": "Jalna - Maharashtra",
"MH25": "Parbhani - Maharashtra",
"MH38": "Hingoli - Maharashtra",
"MH39": "Nandurbar - Maharashtra",
"MH40": "Palghar - Maharashtra",
"MH28": "Pune (old) - Maharashtra",
"MH42": "Dhule (old) - Maharashtra",
"MH44": "Gadchiroli (old) - Maharashtra",
"MH09": "Kolhapur (old) - Maharashtra",
"MH46": "Akola (old) - Maharashtra",
"MH48": "Thane (old) - Maharashtra",
"MH20": "Aurangabad (old) - Maharashtra",
"MH46": "Baramati - Maharashtra",
"MH28": "Beed (old) - Maharashtra",
"MH50": "Buldhana (old) - Maharashtra",
"MH51": "Chandrapur (old) - Maharashtra",
"MH52": "Dhule (old) - Maharashtra",
"MH53": "Gadchiroli (old) - Maharashtra",
"MH54": "Gondia (old) - Maharashtra",
"MH55": "Jalna (old) - Maharashtra",
"MH56": "Kolhapur (old) - Maharashtra",
"MH57": "Nagpur (old) - Maharashtra",
"MH58": "Nanded (old) - Maharashtra",
"MH59": "Nasik (old) - Maharashtra",
"MH60": "Osmanabad (old) - Maharashtra",
"MH61": "Pune (old) - Maharashtra",
"MH62": "Raigad (old) - Maharashtra",
"MH63": "Ratnagiri (old) - Maharashtra",
"MH64": "Sangli (old) - Maharashtra",
"MH65": "Satara (old) - Maharashtra",
"MH66": "Sindhudurg (old) - Maharashtra",
"MH67": "Solapur (old) - Maharashtra",
"MH68": "Thane (old) - Maharashtra",
"MH69": "Wardha (old) - Maharashtra",
"MH70": "Washim (old) - Maharashtra",
"MH71": "Yavatmal (old) - Maharashtra",
"MH46": "Mumbai North - Maharashtra",
"MH47": "Mumbai East - Maharashtra",
"MH48": "Mumbai West - Maharashtra",
"MH49": "Mumbai Central - Maharashtra",
"MH50": "Mumbai South - Maharashtra",
"MN01": "Imphal - Manipur",
"MN02": "Thoubal - Manipur",
"MN03": "Kakching - Manipur",
"MN04": "Churachandpur - Manipur",
"MN05": "Bishnupur - Manipur",
"MN06": "Senapati - Manipur",
"MN07": "Tamenglong - Manipur",
"MN8": "Ukhrul - Manipur",
"MN09": "Chandel - Manipur",
"ML01": "Shillong -  Meghalaya",
"ML02": "Tura -  Meghalaya",
"ML03": "Jowai -  Meghalaya",
"ML04": "Nongpoh -  Meghalaya",
"ML05": "Williamnagar -  Meghalaya",
"MZ01": "Aizawl - Mizoram",
"MZ02": "Lunglei - Mizoram",
"MZ03": "Saiha - Mizoram",
"MZ04": "Champhai - Mizoram",
"MZ05": "Kolasib - Mizoram",
"MZ06": "Serchhip - Mizoram",
"MZ07": "Lawngtlai - Mizoram",
"MZ8": "Mamit - Mizoram",
"NL01": "Kohima - Nagaland",
"NL02": "Dimapur - Nagaland",
"NL03": "Mokokchung - Nagaland",
"NL04": "Tuensang - Nagaland",
"NL05": "Wokha - Nagaland",
"NL06": "Zunheboto - Nagaland",
"NL07": "Mon - Nagaland",
"NL8": "Phek - Nagaland",
"NL09": "Kiphire - Nagaland",
"NL10": "Longleng - Nagaland",
"NL11": "Peren - Nagaland",
"OD02": "Bhubaneswar - Odisha",
"OD05": "Cuttack - Odisha",
"OD10": "Puri - Odisha",
"OD01": "Balasore - Odisha",
"OD07": "Berhampur (Ganjam) - Odisha",
"OD11": "Sambalpur - Odisha",
"OD06": "Rourkela - Odisha",
"OD09": "Bhadrak - Odisha",
"OD04": "Baripada - Odisha",
"OD12": "Jharsuguda - Odisha",
"OD13": "Jeypore (Koraput) - Odisha",
"OD15": "Angul - Odisha",
"OD14": "Rayagada - Odisha",
"OD03": "Dhenkanal - Odisha",
"OD16": "Keonjhar - Odisha",
"OD22": "Jagatsinghpur - Odisha",
"OD25": "Kendrapara - Odisha",
"OD21": "Bargarh - Odisha",
"OD23": "Byasanagar (Jajpur Road) - Odisha",
"OD18": "Jagdalpur (Sundergarh) - Odisha",
"OD24": "Baragarh - Odisha",
"OD20": "Bhawanipatna (Kalahandi) - Odisha",
"OD26": "Phulabani (Kandhamal) - Odisha",
"OD8": "Paradip - Odisha",
"OD27": "Malkangiri - Odisha",
"OD28": "Nabarangpur - Odisha",
"OD29": "Nayagarh - Odisha",
"OD30": "Nuapada - Odisha",
"OD31": "Puri (old) - Odisha",
"OD32": "Sonepur - Odisha",
"OD34": "Umerkote (Nabarangpur) - Odisha",
"OD35": "Ganjam (old) - Odisha",
"OD36": "Sundargarh (old) - Odisha",
"OD37": "Talcher (Angul) - Odisha",
"OD38": "Nayagarh (old) - Odisha",
"OD39": "Phulabani (Kandhamal) (old) - Odisha",
"OD40": "Malkangiri (old) - Odisha",
"OD41": "Koraput (old) - Odisha",
"OD42": "Balangir (old) - Odisha",
"OD43": "Kalahandi (old) - Odisha",
"OD44": "Sundargarh (old) - Odisha",
"OD45": "Sambalpur (old) - Odisha",
"OD46": "Dhenkanal (old) - Odisha",
"OD47": "Keonjhar (old) - Odisha",
"OD48": "Debagarh (Deogarh) - Odisha",
"OD49": "Rayagada (old) - Odisha",
"OD50": "Jajpur (old) - Odisha",
"OD51": "Bhawanipatna (old) - Odisha",
"OD52": "Jagatsinghpur (old) - Odisha",
"OD53": "Bhadrak (old) - Odisha",
"OD54": "Kandhamal (old) - Odisha",
"OD55": "Boudh - Odisha",
"OD56": "Nuapada (old) - Odisha",
"OD57": "Gajapati - Odisha",
"OD58": "Kendrapara (old) - Odisha",
"OD59": "Baragarh (old) - Odisha",
"OD60": "Sonepur (old) - Odisha",
"OD61": "Nabarangpur (old) - Odisha",
"OD62": "Puri (old) - Odisha",
"OD63": "Ganjam (old) - Odisha",
"PB01": "Amritsar - Punjab",
"PB02": "Jalandhar - Punjab",
"PB03": "Ludhiana - Punjab",
"PB04": "Patiala - Punjab",
"PB06": "Gurdaspur - Punjab",
"PB07": "Hoshiarpur - Punjab",
"PB8": "Bhatinda - Punjab",
"PB09": "Kapurthala - Punjab",
"PB10": "Sangrur - Punjab",
"PB11": "Faridkot - Punjab",
"PB12": "Ropar (Rupnagar) - Punjab",
"PB13": "Fatehgarh Sahib - Punjab",
"PB14": "Muktsar - Punjab",
"PB15": "Shahid Bhagat Singh Nagar (Nawanshahr) - Punjab",
"PB16": "Ferozepur - Punjab",
"PB18": "Mansa - Punjab",
"PB19": "Sri Muktsar Sahib - Punjab",
"PB20": "Barnala - Punjab",
"PB21": "Tarn Taran - Punjab",
"PB35": "Pathankot - Punjab",
"PB29": "Moga - Punjab",
"PB36": "Fatehgarh Churian - Punjab",
"PB47": "Sangrur (old) - Punjab",
"PB01": "Amritsar - Rajasthan",
"PB02": "Jalandhar - Rajasthan",
"PB03": "Ludhiana - Rajasthan",
"PB04": "Patiala - Rajasthan",
"PB06": "Gurdaspur - Rajasthan",
"PB07": "Hoshiarpur - Rajasthan",
"PB8": "Bhatinda - Rajasthan",
"PB09": "Kapurthala - Rajasthan",
"PB10": "Sangrur - Rajasthan",
"PB11": "Faridkot - Rajasthan",
"PB12": "Ropar (Rupnagar) - Rajasthan",
"PB13": "Fatehgarh Sahib - Rajasthan",
"PB14": "Muktsar - Rajasthan",
"PB15": "Shahid Bhagat Singh Nagar (Nawanshahr) - Rajasthan",
"PB16": "Ferozepur - Rajasthan",
"PB18": "Mansa - Rajasthan",
"PB19": "Sri Muktsar Sahib - Rajasthan",
"PB20": "Barnala - Rajasthan",
"PB21": "Tarn Taran - Rajasthan",
"PB35": "Pathankot - Rajasthan",
"PB29": "Moga - Rajasthan",
"PB36": "Fatehgarh Churian - Rajasthan",
"PB47": "Sangrur (old) - Rajasthan",
"SK01": "Gangtok - Sikkim",
"SK02": "Rangpo - Sikkim",
"SK03": "Gyalshing (Geyzing) - Sikkim",
"SK04": "Mangan - Sikkim",
"SK05": "Namchi - Sikkim",
"SK06": "Singtam - Sikkim",
"TN01": "Chennai - Tamil Nadu",
"TN38": "Coimbatore - Tamil Nadu",
"TN58": "Madurai - Tamil Nadu",
"TN45": "Tiruchirappalli - Tamil Nadu",
"TN30": "Salem - Tamil Nadu",
"TN72": "Tirunelveli - Tamil Nadu",
"TN23": "Vellore - Tamil Nadu",
"TN37": "Tiruppur - Tamil Nadu",
"TN36": "Erode - Tamil Nadu",
"TN49": "Thanjavur - Tamil Nadu",
"TN57": "Dindigul - Tamil Nadu",
"TN74": "Nagercoil - Tamil Nadu",
"TN31": "Cuddalore - Tamil Nadu",
"TN11": "Kancheepuram - Tamil Nadu",
"TN47": "Karur - Tamil Nadu",
"TN28": "Namakkal - Tamil Nadu",
"TN55": "Pudukkottai - Tamil Nadu",
"TN29": "Dharmapuri - Tamil Nadu",
"TN44": "Krishnagiri - Tamil Nadu",
"TN63": "Sivakasi - Tamil Nadu",
"TN68": "Tiruvarur - Tamil Nadu",
"TN25": "Tiruvannamalai - Tamil Nadu",
"TN32": "Villupuram - Tamil Nadu",
"TN70": "Hosur - Tamil Nadu",
"TN66": "Virudhunagar - Tamil Nadu",
"TN62": "Rajapalayam - Tamil Nadu",
"TN86": "Kumbakonam - Tamil Nadu",
"TN94": "Neyveli - Tamil Nadu",
"TN69": "Tuticorin - Tamil Nadu",
"TN37": "Pollachi - Tamil Nadu",
"TN11": "Nandivaram-Guduvancheri - Tamil Nadu",
"TN18": "Ambattur - Tamil Nadu",
"TN20": "Avadi - Tamil Nadu",
"TN11": "Poonamallee - Tamil Nadu",
"TN96": "Thoothukudi (Tuticorin) - Tamil Nadu",
"TN51": "Nagapattinam - Tamil Nadu",
"TN70": "Krishnagiri (old) - Tamil Nadu",
"TN57": "Theni - Tamil Nadu",
"TN84": "Hosur (old) - Tamil Nadu",
"TN66": "Villupuram (old) - Tamil Nadu",
"TN25": "Vaniyambadi - Tamil Nadu",
"TN68": "Thiruvarur (old) - Tamil Nadu",
"TS01": "Hyderabad (Hyderabad Central) - Telangana",
"TS02": "Secunderabad - Telangana",
"TS03": "Karimnagar - Telangana",
"TS04": "Khammam - Telangana",
"TS05": "Mahabubnagar - Telangana",
"TS06": "Nalgonda - Telangana",
"TS07": "Nizamabad - Telangana",
"TS8": "Adilabad - Telangana",
"TS09": "Warangal - Telangana",
"TS10": "Rangareddy - Telangana",
"TS11": "Medak - Telangana",
"TS12": "Nizamabad (old) - Telangana",
"TS13": "Sangareddy (old) - Telangana",
"TS14": "Karimnagar (old) - Telangana",
"TS15": "Adilabad (old) - Telangana",
"TS16": "Warangal (old) - Telangana",
"TS17": "Khammam (old) - Telangana",
"TS18": "Mahabubnagar (old) - Telangana",
"TS19": "Nalgonda (old) - Telangana",
"TS20": "Medak (old) - Telangana",
"TS01": "Hyderabad (Hyderabad Central) - Tripura",
"TS02": "Secunderabad - Tripura",
"TS03": "Karimnagar - Tripura",
"TS04": "Khammam - Tripura",
"TS05": "Mahabubnagar - Tripura",
"TS06": "Nalgonda - Tripura",
"TS07": "Nizamabad - Tripura",
"TS8": "Adilabad - Tripura",
"TS09": "Warangal - Tripura",
"TS10": "Rangareddy - Tripura",
"TS11": "Medak - Tripura",
"TS12": "Nizamabad (old) - Tripura",
"TS13": "Sangareddy (old) - Tripura",
"TS14": "Karimnagar (old) - Tripura",
"TS15": "Adilabad (old) - Tripura",
"TS16": "Warangal (old) - Tripura",
"TS17": "Khammam (old) - Tripura",
"TS18": "Mahabubnagar (old) - Tripura",
"TS19": "Nalgonda (old) - Tripura",
"TS20": "Medak (old) - Tripura",
"UP80": "Agra - Uttar Pradesh",
"UP81": "Aligarh - Uttar Pradesh",
"UP70": "Allahabad (Prayagraj) - Uttar Pradesh",
"UP45": "Ambedkar Nagar (Akbarpur) - Uttar Pradesh",
"UP72": "Amethi (Sultanpur) - Uttar Pradesh",
"UP23": "Amroha - Uttar Pradesh",
"UP82": "Auraiya - Uttar Pradesh",
"UP47": "Ayodhya (Faizabad) - Uttar Pradesh",
"UP50": "Azamgarh - Uttar Pradesh",
"UP24": "Badaun - Uttar Pradesh",
"UP19": "Baghpat - Uttar Pradesh",
"UP51": "Bahraich - Uttar Pradesh",
"UP52": "Ballia - Uttar Pradesh",
"UP53": "Balrampur - Uttar Pradesh",
"UP71": "Banda - Uttar Pradesh",
"UP54": "Barabanki - Uttar Pradesh",
"UP24": "Bareilly - Uttar Pradesh",
"UP55": "Basti - Uttar Pradesh",
"UP20": "Bijnor - Uttar Pradesh",
"UP21": "Bulandshahr - Uttar Pradesh",
"UP56": "Chandauli - Uttar Pradesh",
"UP57": "Chitrakoot - Uttar Pradesh",
"UP58": "Deoria - Uttar Pradesh",
"UP22": "Etah - Uttar Pradesh",
"UP59": "Etawah - Uttar Pradesh",
"UP47": "Faizabad (Ayodhya) - Uttar Pradesh",
"UP60": "Farrukhabad - Uttar Pradesh",
"UP61": "Fatehpur - Uttar Pradesh",
"UP62": "Firozabad - Uttar Pradesh",
"UP16": "Gautam Buddh Nagar (Noida) - Uttar Pradesh",
"UP14": "Ghaziabad - Uttar Pradesh",
"UP63": "Ghazipur - Uttar Pradesh",
"UP64": "Gonda - Uttar Pradesh",
"UP65": "Gorakhpur - Uttar Pradesh",
"UP66": "Hamirpur - Uttar Pradesh",
"UP15": "Hapur - Uttar Pradesh",
"UP25": "Hardoi - Uttar Pradesh",
"UP23": "Hathras - Uttar Pradesh",
"UP67": "Jalaun (Orai) - Uttar Pradesh",
"UP68": "Jaunpur - Uttar Pradesh",
"UP26": "Jhansi - Uttar Pradesh",
"UP27": "Kannauj - Uttar Pradesh",
"UP78": "Kanpur - Uttar Pradesh",
"UP24": "Kasganj - Uttar Pradesh",
"UP69": "Kaushambi - Uttar Pradesh",
"UP70": "Kushinagar - Uttar Pradesh",
"UP71": "Lakhimpur Kheri - Uttar Pradesh",
"UP28": "Lalitpur - Uttar Pradesh",
"UP32": "Lucknow - Uttar Pradesh",
"UP72": "Maharajganj - Uttar Pradesh",
"UP73": "Mahoba - Uttar Pradesh",
"UP29": "Mainpuri - Uttar Pradesh",
"UP30": "Mathura - Uttar Pradesh",
"UP74": "Mau - Uttar Pradesh",
"UP20": "Meerut - Uttar Pradesh",
"UP75": "Mirzapur - Uttar Pradesh",
"UP21": "Moradabad - Uttar Pradesh",
"UP22": "Muzaffarnagar - Uttar Pradesh",
"UP76": "Pilibhit - Uttar Pradesh",
"UP77": "Pratapgarh - Uttar Pradesh",
"UP78": "Raebareli - Uttar Pradesh",
"UP23": "Rampur - Uttar Pradesh",
"UP24": "Saharanpur - Uttar Pradesh",
"UP79": "Sambhal - Uttar Pradesh",
"UP46": "Sant Kabir Nagar (Khalilabad) - Uttar Pradesh",
"UP25": "Shahjahanpur - Uttar Pradesh",
"UP26": "Shamli - Uttar Pradesh",
"UP80": "Shravasti - Uttar Pradesh",
"UP81": "Siddharthnagar - Uttar Pradesh",
"UP82": "Sitapur - Uttar Pradesh",
"UP83": "Sonbhadra - Uttar Pradesh",
"UP84": "Sultanpur - Uttar Pradesh",
"UP27": "Unnao - Uttar Pradesh",
"UP65": "Varanasi - Uttar Pradesh",
"UP03": "Baghpat (old) - Uttar Pradesh",
"UP05": "Bahraich (old) - Uttar Pradesh",
"UP12": "Banda (old) - Uttar Pradesh",
"UP8": "Bijnor (old) - Uttar Pradesh",
"UP04": "Budaun (old) - Uttar Pradesh",
"UP06": "Chandauli (old) - Uttar Pradesh",
"UP10": "Chitrakoot (old) - Uttar Pradesh",
"UP07": "Deoria (old) - Uttar Pradesh",
"UP09": "Etah (old) - Uttar Pradesh",
"UP11": "Fatehpur (old) - Uttar Pradesh",
"UP13": "Ghazipur (old) - Uttar Pradesh",
"UP15": "Gorakhpur (old) - Uttar Pradesh",
"UP16": "Hamirpur (old) - Uttar Pradesh",
"UP18": "Jalaun (Orai) (old) - Uttar Pradesh",
"UP19": "Jaunpur (old) - Uttar Pradesh",
"UP21": "Kannauj (old) - Uttar Pradesh",
"UP24": "Kanpur (old) - Uttar Pradesh",
"UP25": "Kasganj (old) - Uttar Pradesh",
"UP29": "Kushinagar (old) - Uttar Pradesh",
"UP31": "Lakhimpur Kheri (old) - Uttar Pradesh",
"UP34": "Mathura (old) - Uttar Pradesh",
"UP36": "Muzaffarnagar (old) - Uttar Pradesh",
"UP39": "Pilibhit (old) - Uttar Pradesh",
"UP40": "Pratapgarh (old) - Uttar Pradesh",
"UP41": "Raebareli (old) - Uttar Pradesh",
"UP42": "Rampur (old) - Uttar Pradesh",
"UP43": "Sambhal (old) - Uttar Pradesh",
"UP44": "Shamli (old) - Uttar Pradesh",
"UP45": "Shravasti (old) - Uttar Pradesh",
"UP46": "Siddharthnagar (old) - Uttar Pradesh",
"UP47": "Sitapur (old) - Uttar Pradesh",
"UP48": "Sonbhadra (old) - Uttar Pradesh",
"UP49": "Sultanpur (old) - Uttar Pradesh",
"UP50": "Unnao (old) - Uttar Pradesh",
"UP51": "Varanasi (old) - Uttar Pradesh",
"UK07": "Dehradun - Uttarakhand",
"UK8": "Haridwar - Uttarakhand",
"UK09": "Rishikesh - Uttarakhand",
"UK11": "Haldwani - Uttarakhand",
"UK12": "Nainital - Uttarakhand",
"UK01": "Almora - Uttarakhand",
"UK02": "Pithoragarh - Uttarakhand",
"UK03": "Bageshwar - Uttarakhand",
"UK04": "Champawat - Uttarakhand",
"UK05": "Nainital (old) - Uttarakhand",
"UK10": "Rudrapur - Uttarakhand",
"UK06": "Kashipur - Uttarakhand",
"UK13": "Tehri - Uttarakhand",
"UK14": "Roorkee - Uttarakhand",
"UK15": "Khatima - Uttarakhand",
"WB01": "Kolkata - West Bengal",
"WB02": "North 24 Parganas (Barasat) - West Bengal",
"WB03": "South 24 Parganas (Alipore) - West Bengal",
"WB04": "Howrah - West Bengal",
"WB05": "Hooghly (Chinsurah) - West Bengal",
"WB06": "Nadia (Krishnanagar) - West Bengal",
"WB07": "Murshidabad (Berhampore) - West Bengal",
"WB8": "Birbhum (Suri) - West Bengal",
"WB09": "Bankura - West Bengal",
"WB10": "Purulia - West Bengal",
"WB11": "Midnapore (Paschim Medinipur) - West Bengal",
"WB12": "Purba Medinipur (Tamluk) - West Bengal",
"WB13": "Burdwan (Bardhaman) - West Bengal",
"WB14": "Birbhum (old) - West Bengal",
"WB15": "Nadia (Krishnanagar) (old) - West Bengal",
"WB16": "North 24 Parganas (Barasat) (old) - West Bengal",
"WB17": "South 24 Parganas (Alipore) (old) - West Bengal",
"WB18": "Midnapore (Paschim Medinipur) (old) - West Bengal",
"WB19": "Bankura (old) - West Bengal",
"WB20": "Purulia (old) - West Bengal",
"WB21": "Howrah (old) - West Bengal",
"WB22": "Hooghly (Chinsurah) (old) - West Bengal",
"WB23": "Burdwan (Bardhaman) (old) - West Bengal",
"WB24": "Purba Medinipur (Tamluk) (old) - West Bengal",
"WB25": "Cooch Behar - West Bengal",
"WB26": "Jalpaiguri - West Bengal",
"WB27": "Darjeeling - West Bengal",
"WB28": "North Dinajpur (Raiganj) - West Bengal",
"WB29": "South Dinajpur (Balurghat) - West Bengal",
"WB30": "Malda - West Bengal",
"WB31": "Murshidabad (Berhampore) (old) - West Bengal",
"WB32": "Jalpaiguri (old) - West Bengal",
"WB33": "Darjeeling (old) - West Bengal",
"WB34": "North Dinajpur (Raiganj) (old) - West Bengal",
"WB35": "South Dinajpur (Balurghat) (old) - West Bengal",
"WB36": "Malda (old) - West Bengal",
"WB37": "Kolkata (old) - West Bengal"
}


searchCity.addEventListener("click", function(){
    const vCode = vehicleCode.value.trim().toUpperCase();
    const ctyCode = vehicledata[vCode] ;

    if(ctyCode){
       cityresult.innerHTML = ` ${vCode} code is used in <br> ${ctyCode}`;
       cityresult.style.display = "flex"; 
    }else{
        cityresult.textContent = "City not found for the given vehicle code.";
        cityresult.style.display = "flex";
    }
});

reset.addEventListener("click", function(){
cityresult.style.display = "none";
vehicleCode.value = "";
});